# 地域节点
aliyun:
  endPoint: oss-cn-shanghai.aliyuncs.com
  # Bucket 域名
  urlPrefix: lyh-test-xupt.oss-cn-shanghai.aliyuncs.com
  # accessKey Id
  accessKeyId: LTAI5tJKuFS5hP4mtpas4uyy
  # accessKey Secret
  accessKeySecret: cXW87wLue0bvEH1on8L3jsLD01ZzhU
  # 你的Bucket名称
  bucketName: zsxb-ttms
  # 目标文件夹
  fileHost: play

