server:
  port: 9090
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource      # 数据源的类型，可以更改为其他的数据源配置，比如druid
    driver-class-name: com.mysql.cj.jdbc.Driver      # mysql/MariaDB 的数据库驱动类名称
    url: jdbc:mysql://121.37.155.73:7777/zsxb?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: ymxkai0.1
    hikari:
      connection-timeout: 30000               # 等待连接池分配连接的最大时间（毫秒），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                         # 最小连接数
      maximum-pool-size: 20                   # 最大连接数
      auto-commit: true                       # 自动提交
      idle-timeout: 600000                    # 连接超时的最大时长（毫秒），超时则会被释放（retired）
      pool-name: DataSourceHikariCP           # 连接池的名字
      max-lifetime: 18000000                  # 连接池的最大生命时长（毫秒），超时则会被释放（retired）
      connection-test-query: SELECT 1

  redis:
    host: 121.37.155.73
    port: 6379
    database: 15
    password: redis123

root:
  username: root
  password: root

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete #默认deleted
      logic-delete-value: 1 # 1为删除
      logic-not-delete-value: 0 # 0为未删除
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true # 自动驼峰映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  mapper-locations: classpath:mapper/*.xml  # 扫描xml路径

# 日志文件配置路径
logging:
  config: classpath:log4j2-dev.xml
  level:
    com.zsxb.mapper: debug
    web: debug
    sql: debug


